#include <cstdint>
#include <string_view>
namespace asm_lex
{
using token_type_t = std::uint16_t;
constexpr token_type_t TOK_ERROR = 0;
constexpr token_type_t TOK_ADC = 1;
constexpr token_type_t TOK_AND = 2;
constexpr token_type_t TOK_ASL = 3;
constexpr token_type_t TOK_BCC = 4;
constexpr token_type_t TOK_BCS = 5;
constexpr token_type_t TOK_BEQ = 6;
constexpr token_type_t TOK_BIT = 7;
constexpr token_type_t TOK_BMI = 8;
constexpr token_type_t TOK_BNE = 9;
constexpr token_type_t TOK_BPL = 10;
constexpr token_type_t TOK_BRK = 11;
constexpr token_type_t TOK_BVC = 12;
constexpr token_type_t TOK_BVS = 13;
constexpr token_type_t TOK_CLC = 14;
constexpr token_type_t TOK_CLD = 15;
constexpr token_type_t TOK_CLI = 16;
constexpr token_type_t TOK_CLV = 17;
constexpr token_type_t TOK_CMP = 18;
constexpr token_type_t TOK_CPX = 19;
constexpr token_type_t TOK_CPY = 20;
constexpr token_type_t TOK_DEC = 21;
constexpr token_type_t TOK_DEX = 22;
constexpr token_type_t TOK_DEY = 23;
constexpr token_type_t TOK_EOR = 24;
constexpr token_type_t TOK_INC = 25;
constexpr token_type_t TOK_INX = 26;
constexpr token_type_t TOK_INY = 27;
constexpr token_type_t TOK_JMP = 28;
constexpr token_type_t TOK_JSR = 29;
constexpr token_type_t TOK_LDA = 30;
constexpr token_type_t TOK_LDX = 31;
constexpr token_type_t TOK_LDY = 32;
constexpr token_type_t TOK_LSR = 33;
constexpr token_type_t TOK_NOP = 34;
constexpr token_type_t TOK_ORA = 35;
constexpr token_type_t TOK_PHA = 36;
constexpr token_type_t TOK_PHP = 37;
constexpr token_type_t TOK_PLA = 38;
constexpr token_type_t TOK_PLP = 39;
constexpr token_type_t TOK_ROL = 40;
constexpr token_type_t TOK_ROR = 41;
constexpr token_type_t TOK_RTI = 42;
constexpr token_type_t TOK_RTS = 43;
constexpr token_type_t TOK_SBC = 44;
constexpr token_type_t TOK_SEC = 45;
constexpr token_type_t TOK_SED = 46;
constexpr token_type_t TOK_SEI = 47;
constexpr token_type_t TOK_STA = 48;
constexpr token_type_t TOK_STX = 49;
constexpr token_type_t TOK_STY = 50;
constexpr token_type_t TOK_TAX = 51;
constexpr token_type_t TOK_TAY = 52;
constexpr token_type_t TOK_TSX = 53;
constexpr token_type_t TOK_TXA = 54;
constexpr token_type_t TOK_TXS = 55;
constexpr token_type_t TOK_TYA = 56;
constexpr token_type_t TOK_LAX = 57;
constexpr token_type_t TOK_AXS = 58;
constexpr token_type_t TOK_ANC = 59;
constexpr token_type_t TOK_ALR = 60;
constexpr token_type_t TOK_ARR = 61;
constexpr token_type_t TOK_SKB = 62;
constexpr token_type_t TOK_IGN = 63;
constexpr token_type_t TOK_DCP = 64;
constexpr token_type_t TOK_ISC = 65;
constexpr token_type_t TOK_RLA = 66;
constexpr token_type_t TOK_RRA = 67;
constexpr token_type_t TOK_SLO = 68;
constexpr token_type_t TOK_SRE = 69;
constexpr token_type_t TOK_BRA = 70;
constexpr token_type_t TOK_PHX = 71;
constexpr token_type_t TOK_PHY = 72;
constexpr token_type_t TOK_PLX = 73;
constexpr token_type_t TOK_PLY = 74;
constexpr token_type_t TOK_TXY = 75;
constexpr token_type_t TOK_TYX = 76;
constexpr token_type_t TOK_TRB = 77;
constexpr token_type_t TOK_TSB = 78;
constexpr token_type_t TOK_STZ = 79;
constexpr token_type_t TOK_BRL = 80;
constexpr token_type_t TOK_JSL = 81;
constexpr token_type_t TOK_RTL = 82;
constexpr token_type_t TOK_COP = 83;
constexpr token_type_t TOK_REP = 84;
constexpr token_type_t TOK_SEP = 85;
constexpr token_type_t TOK_MVN = 86;
constexpr token_type_t TOK_MVP = 87;
constexpr token_type_t TOK_WDM = 88;
constexpr token_type_t TOK_PEA = 89;
constexpr token_type_t TOK_PEI = 90;
constexpr token_type_t TOK_PER = 91;
constexpr token_type_t TOK_PHB = 92;
constexpr token_type_t TOK_PHD = 93;
constexpr token_type_t TOK_PHK = 94;
constexpr token_type_t TOK_PLB = 95;
constexpr token_type_t TOK_PLD = 96;
constexpr token_type_t TOK_PLK = 97;
constexpr token_type_t TOK_STP = 98;
constexpr token_type_t TOK_WAI = 99;
constexpr token_type_t TOK_TCD = 100;
constexpr token_type_t TOK_TCS = 101;
constexpr token_type_t TOK_TDC = 102;
constexpr token_type_t TOK_TSC = 103;
constexpr token_type_t TOK_XBA = 104;
constexpr token_type_t TOK_XCE = 105;
constexpr token_type_t TOK_BBR0 = 106;
constexpr token_type_t TOK_BBR1 = 107;
constexpr token_type_t TOK_BBR2 = 108;
constexpr token_type_t TOK_BBR3 = 109;
constexpr token_type_t TOK_BBR4 = 110;
constexpr token_type_t TOK_BBR5 = 111;
constexpr token_type_t TOK_BBR6 = 112;
constexpr token_type_t TOK_BBR7 = 113;
constexpr token_type_t TOK_BBS0 = 114;
constexpr token_type_t TOK_BBS1 = 115;
constexpr token_type_t TOK_BBS2 = 116;
constexpr token_type_t TOK_BBS3 = 117;
constexpr token_type_t TOK_BBS4 = 118;
constexpr token_type_t TOK_BBS5 = 119;
constexpr token_type_t TOK_BBS6 = 120;
constexpr token_type_t TOK_BBS7 = 121;
constexpr token_type_t TOK_RMB0 = 122;
constexpr token_type_t TOK_RMB1 = 123;
constexpr token_type_t TOK_RMB2 = 124;
constexpr token_type_t TOK_RMB3 = 125;
constexpr token_type_t TOK_RMB4 = 126;
constexpr token_type_t TOK_RMB5 = 127;
constexpr token_type_t TOK_RMB6 = 128;
constexpr token_type_t TOK_RMB7 = 129;
constexpr token_type_t TOK_SMB0 = 130;
constexpr token_type_t TOK_SMB1 = 131;
constexpr token_type_t TOK_SMB2 = 132;
constexpr token_type_t TOK_SMB3 = 133;
constexpr token_type_t TOK_SMB4 = 134;
constexpr token_type_t TOK_SMB5 = 135;
constexpr token_type_t TOK_SMB6 = 136;
constexpr token_type_t TOK_SMB7 = 137;
constexpr token_type_t TOK_MPR0 = 138;
constexpr token_type_t TOK_MPR1 = 139;
constexpr token_type_t TOK_MPR2 = 140;
constexpr token_type_t TOK_MPR3 = 141;
constexpr token_type_t TOK_MPR4 = 142;
constexpr token_type_t TOK_MPR5 = 143;
constexpr token_type_t TOK_MPR6 = 144;
constexpr token_type_t TOK_MPR7 = 145;
constexpr token_type_t TOK_TMA0 = 146;
constexpr token_type_t TOK_TMA1 = 147;
constexpr token_type_t TOK_TMA2 = 148;
constexpr token_type_t TOK_TMA3 = 149;
constexpr token_type_t TOK_TMA4 = 150;
constexpr token_type_t TOK_TMA5 = 151;
constexpr token_type_t TOK_TMA6 = 152;
constexpr token_type_t TOK_TMA7 = 153;
constexpr token_type_t TOK_BSR = 154;
constexpr token_type_t TOK_CLA = 155;
constexpr token_type_t TOK_CLX = 156;
constexpr token_type_t TOK_CLY = 157;
constexpr token_type_t TOK_CSH = 158;
constexpr token_type_t TOK_CSL = 159;
constexpr token_type_t TOK_SAX = 160;
constexpr token_type_t TOK_SXY = 161;
constexpr token_type_t TOK_SYA = 162;
constexpr token_type_t TOK_SET = 163;
constexpr token_type_t TOK_ST0 = 164;
constexpr token_type_t TOK_ST1 = 165;
constexpr token_type_t TOK_ST2 = 166;
constexpr token_type_t TOK_TAI = 167;
constexpr token_type_t TOK_TIA = 168;
constexpr token_type_t TOK_TDD = 169;
constexpr token_type_t TOK_TIN = 170;
constexpr token_type_t TOK_TII = 171;
constexpr token_type_t TOK_TST = 172;
constexpr token_type_t TOK_eof = 173;
constexpr token_type_t TOK_END = 174;
inline std::string_view token_name(token_type_t type)
{
    using namespace std::literals;
    switch(type)
    {
    default: return "?BAD?"sv;
    case TOK_ADC: return "ADC"sv;
    case TOK_AND: return "AND"sv;
    case TOK_ASL: return "ASL"sv;
    case TOK_BCC: return "BCC"sv;
    case TOK_BCS: return "BCS"sv;
    case TOK_BEQ: return "BEQ"sv;
    case TOK_BIT: return "BIT"sv;
    case TOK_BMI: return "BMI"sv;
    case TOK_BNE: return "BNE"sv;
    case TOK_BPL: return "BPL"sv;
    case TOK_BRK: return "BRK"sv;
    case TOK_BVC: return "BVC"sv;
    case TOK_BVS: return "BVS"sv;
    case TOK_CLC: return "CLC"sv;
    case TOK_CLD: return "CLD"sv;
    case TOK_CLI: return "CLI"sv;
    case TOK_CLV: return "CLV"sv;
    case TOK_CMP: return "CMP"sv;
    case TOK_CPX: return "CPX"sv;
    case TOK_CPY: return "CPY"sv;
    case TOK_DEC: return "DEC"sv;
    case TOK_DEX: return "DEX"sv;
    case TOK_DEY: return "DEY"sv;
    case TOK_EOR: return "EOR"sv;
    case TOK_INC: return "INC"sv;
    case TOK_INX: return "INX"sv;
    case TOK_INY: return "INY"sv;
    case TOK_JMP: return "JMP"sv;
    case TOK_JSR: return "JSR"sv;
    case TOK_LDA: return "LDA"sv;
    case TOK_LDX: return "LDX"sv;
    case TOK_LDY: return "LDY"sv;
    case TOK_LSR: return "LSR"sv;
    case TOK_NOP: return "NOP"sv;
    case TOK_ORA: return "ORA"sv;
    case TOK_PHA: return "PHA"sv;
    case TOK_PHP: return "PHP"sv;
    case TOK_PLA: return "PLA"sv;
    case TOK_PLP: return "PLP"sv;
    case TOK_ROL: return "ROL"sv;
    case TOK_ROR: return "ROR"sv;
    case TOK_RTI: return "RTI"sv;
    case TOK_RTS: return "RTS"sv;
    case TOK_SBC: return "SBC"sv;
    case TOK_SEC: return "SEC"sv;
    case TOK_SED: return "SED"sv;
    case TOK_SEI: return "SEI"sv;
    case TOK_STA: return "STA"sv;
    case TOK_STX: return "STX"sv;
    case TOK_STY: return "STY"sv;
    case TOK_TAX: return "TAX"sv;
    case TOK_TAY: return "TAY"sv;
    case TOK_TSX: return "TSX"sv;
    case TOK_TXA: return "TXA"sv;
    case TOK_TXS: return "TXS"sv;
    case TOK_TYA: return "TYA"sv;
    case TOK_LAX: return "LAX"sv;
    case TOK_AXS: return "AXS"sv;
    case TOK_ANC: return "ANC"sv;
    case TOK_ALR: return "ALR"sv;
    case TOK_ARR: return "ARR"sv;
    case TOK_SKB: return "SKB"sv;
    case TOK_IGN: return "IGN"sv;
    case TOK_DCP: return "DCP"sv;
    case TOK_ISC: return "ISC"sv;
    case TOK_RLA: return "RLA"sv;
    case TOK_RRA: return "RRA"sv;
    case TOK_SLO: return "SLO"sv;
    case TOK_SRE: return "SRE"sv;
    case TOK_BRA: return "BRA"sv;
    case TOK_PHX: return "PHX"sv;
    case TOK_PHY: return "PHY"sv;
    case TOK_PLX: return "PLX"sv;
    case TOK_PLY: return "PLY"sv;
    case TOK_TXY: return "TXY"sv;
    case TOK_TYX: return "TYX"sv;
    case TOK_TRB: return "TRB"sv;
    case TOK_TSB: return "TSB"sv;
    case TOK_STZ: return "STZ"sv;
    case TOK_BRL: return "BRL"sv;
    case TOK_JSL: return "JSL"sv;
    case TOK_RTL: return "RTL"sv;
    case TOK_COP: return "COP"sv;
    case TOK_REP: return "REP"sv;
    case TOK_SEP: return "SEP"sv;
    case TOK_MVN: return "MVN"sv;
    case TOK_MVP: return "MVP"sv;
    case TOK_WDM: return "WDM"sv;
    case TOK_PEA: return "PEA"sv;
    case TOK_PEI: return "PEI"sv;
    case TOK_PER: return "PER"sv;
    case TOK_PHB: return "PHB"sv;
    case TOK_PHD: return "PHD"sv;
    case TOK_PHK: return "PHK"sv;
    case TOK_PLB: return "PLB"sv;
    case TOK_PLD: return "PLD"sv;
    case TOK_PLK: return "PLK"sv;
    case TOK_STP: return "STP"sv;
    case TOK_WAI: return "WAI"sv;
    case TOK_TCD: return "TCD"sv;
    case TOK_TCS: return "TCS"sv;
    case TOK_TDC: return "TDC"sv;
    case TOK_TSC: return "TSC"sv;
    case TOK_XBA: return "XBA"sv;
    case TOK_XCE: return "XCE"sv;
    case TOK_BBR0: return "BBR0"sv;
    case TOK_BBR1: return "BBR1"sv;
    case TOK_BBR2: return "BBR2"sv;
    case TOK_BBR3: return "BBR3"sv;
    case TOK_BBR4: return "BBR4"sv;
    case TOK_BBR5: return "BBR5"sv;
    case TOK_BBR6: return "BBR6"sv;
    case TOK_BBR7: return "BBR7"sv;
    case TOK_BBS0: return "BBS0"sv;
    case TOK_BBS1: return "BBS1"sv;
    case TOK_BBS2: return "BBS2"sv;
    case TOK_BBS3: return "BBS3"sv;
    case TOK_BBS4: return "BBS4"sv;
    case TOK_BBS5: return "BBS5"sv;
    case TOK_BBS6: return "BBS6"sv;
    case TOK_BBS7: return "BBS7"sv;
    case TOK_RMB0: return "RMB0"sv;
    case TOK_RMB1: return "RMB1"sv;
    case TOK_RMB2: return "RMB2"sv;
    case TOK_RMB3: return "RMB3"sv;
    case TOK_RMB4: return "RMB4"sv;
    case TOK_RMB5: return "RMB5"sv;
    case TOK_RMB6: return "RMB6"sv;
    case TOK_RMB7: return "RMB7"sv;
    case TOK_SMB0: return "SMB0"sv;
    case TOK_SMB1: return "SMB1"sv;
    case TOK_SMB2: return "SMB2"sv;
    case TOK_SMB3: return "SMB3"sv;
    case TOK_SMB4: return "SMB4"sv;
    case TOK_SMB5: return "SMB5"sv;
    case TOK_SMB6: return "SMB6"sv;
    case TOK_SMB7: return "SMB7"sv;
    case TOK_MPR0: return "MPR0"sv;
    case TOK_MPR1: return "MPR1"sv;
    case TOK_MPR2: return "MPR2"sv;
    case TOK_MPR3: return "MPR3"sv;
    case TOK_MPR4: return "MPR4"sv;
    case TOK_MPR5: return "MPR5"sv;
    case TOK_MPR6: return "MPR6"sv;
    case TOK_MPR7: return "MPR7"sv;
    case TOK_TMA0: return "TMA0"sv;
    case TOK_TMA1: return "TMA1"sv;
    case TOK_TMA2: return "TMA2"sv;
    case TOK_TMA3: return "TMA3"sv;
    case TOK_TMA4: return "TMA4"sv;
    case TOK_TMA5: return "TMA5"sv;
    case TOK_TMA6: return "TMA6"sv;
    case TOK_TMA7: return "TMA7"sv;
    case TOK_BSR: return "BSR"sv;
    case TOK_CLA: return "CLA"sv;
    case TOK_CLX: return "CLX"sv;
    case TOK_CLY: return "CLY"sv;
    case TOK_CSH: return "CSH"sv;
    case TOK_CSL: return "CSL"sv;
    case TOK_SAX: return "SAX"sv;
    case TOK_SXY: return "SXY"sv;
    case TOK_SYA: return "SYA"sv;
    case TOK_SET: return "SET"sv;
    case TOK_ST0: return "ST0"sv;
    case TOK_ST1: return "ST1"sv;
    case TOK_ST2: return "ST2"sv;
    case TOK_TAI: return "TAI"sv;
    case TOK_TIA: return "TIA"sv;
    case TOK_TDD: return "TDD"sv;
    case TOK_TIN: return "TIN"sv;
    case TOK_TII: return "TII"sv;
    case TOK_TST: return "TST"sv;
    case TOK_eof: return "eof"sv;
    }
}
inline std::string_view token_string(token_type_t type)
{
    using namespace std::literals;
    switch(type)
    {
    default: return "?BAD?"sv;
    case TOK_ADC: return "ADC"sv;
    case TOK_AND: return "AND"sv;
    case TOK_ASL: return "ASL"sv;
    case TOK_BCC: return "BCC"sv;
    case TOK_BCS: return "BCS"sv;
    case TOK_BEQ: return "BEQ"sv;
    case TOK_BIT: return "BIT"sv;
    case TOK_BMI: return "BMI"sv;
    case TOK_BNE: return "BNE"sv;
    case TOK_BPL: return "BPL"sv;
    case TOK_BRK: return "BRK"sv;
    case TOK_BVC: return "BVC"sv;
    case TOK_BVS: return "BVS"sv;
    case TOK_CLC: return "CLC"sv;
    case TOK_CLD: return "CLD"sv;
    case TOK_CLI: return "CLI"sv;
    case TOK_CLV: return "CLV"sv;
    case TOK_CMP: return "CMP"sv;
    case TOK_CPX: return "CPX"sv;
    case TOK_CPY: return "CPY"sv;
    case TOK_DEC: return "DEC"sv;
    case TOK_DEX: return "DEX"sv;
    case TOK_DEY: return "DEY"sv;
    case TOK_EOR: return "EOR"sv;
    case TOK_INC: return "INC"sv;
    case TOK_INX: return "INX"sv;
    case TOK_INY: return "INY"sv;
    case TOK_JMP: return "JMP"sv;
    case TOK_JSR: return "JSR"sv;
    case TOK_LDA: return "LDA"sv;
    case TOK_LDX: return "LDX"sv;
    case TOK_LDY: return "LDY"sv;
    case TOK_LSR: return "LSR"sv;
    case TOK_NOP: return "NOP"sv;
    case TOK_ORA: return "ORA"sv;
    case TOK_PHA: return "PHA"sv;
    case TOK_PHP: return "PHP"sv;
    case TOK_PLA: return "PLA"sv;
    case TOK_PLP: return "PLP"sv;
    case TOK_ROL: return "ROL"sv;
    case TOK_ROR: return "ROR"sv;
    case TOK_RTI: return "RTI"sv;
    case TOK_RTS: return "RTS"sv;
    case TOK_SBC: return "SBC"sv;
    case TOK_SEC: return "SEC"sv;
    case TOK_SED: return "SED"sv;
    case TOK_SEI: return "SEI"sv;
    case TOK_STA: return "STA"sv;
    case TOK_STX: return "STX"sv;
    case TOK_STY: return "STY"sv;
    case TOK_TAX: return "TAX"sv;
    case TOK_TAY: return "TAY"sv;
    case TOK_TSX: return "TSX"sv;
    case TOK_TXA: return "TXA"sv;
    case TOK_TXS: return "TXS"sv;
    case TOK_TYA: return "TYA"sv;
    case TOK_LAX: return "LAX"sv;
    case TOK_AXS: return "AXS"sv;
    case TOK_ANC: return "ANC"sv;
    case TOK_ALR: return "ALR"sv;
    case TOK_ARR: return "ARR"sv;
    case TOK_SKB: return "SKB"sv;
    case TOK_IGN: return "IGN"sv;
    case TOK_DCP: return "DCP"sv;
    case TOK_ISC: return "ISC"sv;
    case TOK_RLA: return "RLA"sv;
    case TOK_RRA: return "RRA"sv;
    case TOK_SLO: return "SLO"sv;
    case TOK_SRE: return "SRE"sv;
    case TOK_BRA: return "BRA"sv;
    case TOK_PHX: return "PHX"sv;
    case TOK_PHY: return "PHY"sv;
    case TOK_PLX: return "PLX"sv;
    case TOK_PLY: return "PLY"sv;
    case TOK_TXY: return "TXY"sv;
    case TOK_TYX: return "TYX"sv;
    case TOK_TRB: return "TRB"sv;
    case TOK_TSB: return "TSB"sv;
    case TOK_STZ: return "STZ"sv;
    case TOK_BRL: return "BRL"sv;
    case TOK_JSL: return "JSL"sv;
    case TOK_RTL: return "RTL"sv;
    case TOK_COP: return "COP"sv;
    case TOK_REP: return "REP"sv;
    case TOK_SEP: return "SEP"sv;
    case TOK_MVN: return "MVN"sv;
    case TOK_MVP: return "MVP"sv;
    case TOK_WDM: return "WDM"sv;
    case TOK_PEA: return "PEA"sv;
    case TOK_PEI: return "PEI"sv;
    case TOK_PER: return "PER"sv;
    case TOK_PHB: return "PHB"sv;
    case TOK_PHD: return "PHD"sv;
    case TOK_PHK: return "PHK"sv;
    case TOK_PLB: return "PLB"sv;
    case TOK_PLD: return "PLD"sv;
    case TOK_PLK: return "PLK"sv;
    case TOK_STP: return "STP"sv;
    case TOK_WAI: return "WAI"sv;
    case TOK_TCD: return "TCD"sv;
    case TOK_TCS: return "TCS"sv;
    case TOK_TDC: return "TDC"sv;
    case TOK_TSC: return "TSC"sv;
    case TOK_XBA: return "XBA"sv;
    case TOK_XCE: return "XCE"sv;
    case TOK_BBR0: return "BBR0"sv;
    case TOK_BBR1: return "BBR1"sv;
    case TOK_BBR2: return "BBR2"sv;
    case TOK_BBR3: return "BBR3"sv;
    case TOK_BBR4: return "BBR4"sv;
    case TOK_BBR5: return "BBR5"sv;
    case TOK_BBR6: return "BBR6"sv;
    case TOK_BBR7: return "BBR7"sv;
    case TOK_BBS0: return "BBS0"sv;
    case TOK_BBS1: return "BBS1"sv;
    case TOK_BBS2: return "BBS2"sv;
    case TOK_BBS3: return "BBS3"sv;
    case TOK_BBS4: return "BBS4"sv;
    case TOK_BBS5: return "BBS5"sv;
    case TOK_BBS6: return "BBS6"sv;
    case TOK_BBS7: return "BBS7"sv;
    case TOK_RMB0: return "RMB0"sv;
    case TOK_RMB1: return "RMB1"sv;
    case TOK_RMB2: return "RMB2"sv;
    case TOK_RMB3: return "RMB3"sv;
    case TOK_RMB4: return "RMB4"sv;
    case TOK_RMB5: return "RMB5"sv;
    case TOK_RMB6: return "RMB6"sv;
    case TOK_RMB7: return "RMB7"sv;
    case TOK_SMB0: return "SMB0"sv;
    case TOK_SMB1: return "SMB1"sv;
    case TOK_SMB2: return "SMB2"sv;
    case TOK_SMB3: return "SMB3"sv;
    case TOK_SMB4: return "SMB4"sv;
    case TOK_SMB5: return "SMB5"sv;
    case TOK_SMB6: return "SMB6"sv;
    case TOK_SMB7: return "SMB7"sv;
    case TOK_MPR0: return "MPR0"sv;
    case TOK_MPR1: return "MPR1"sv;
    case TOK_MPR2: return "MPR2"sv;
    case TOK_MPR3: return "MPR3"sv;
    case TOK_MPR4: return "MPR4"sv;
    case TOK_MPR5: return "MPR5"sv;
    case TOK_MPR6: return "MPR6"sv;
    case TOK_MPR7: return "MPR7"sv;
    case TOK_TMA0: return "TMA0"sv;
    case TOK_TMA1: return "TMA1"sv;
    case TOK_TMA2: return "TMA2"sv;
    case TOK_TMA3: return "TMA3"sv;
    case TOK_TMA4: return "TMA4"sv;
    case TOK_TMA5: return "TMA5"sv;
    case TOK_TMA6: return "TMA6"sv;
    case TOK_TMA7: return "TMA7"sv;
    case TOK_BSR: return "BSR"sv;
    case TOK_CLA: return "CLA"sv;
    case TOK_CLX: return "CLX"sv;
    case TOK_CLY: return "CLY"sv;
    case TOK_CSH: return "CSH"sv;
    case TOK_CSL: return "CSL"sv;
    case TOK_SAX: return "SAX"sv;
    case TOK_SXY: return "SXY"sv;
    case TOK_SYA: return "SYA"sv;
    case TOK_SET: return "SET"sv;
    case TOK_ST0: return "ST0"sv;
    case TOK_ST1: return "ST1"sv;
    case TOK_ST2: return "ST2"sv;
    case TOK_TAI: return "TAI"sv;
    case TOK_TIA: return "TIA"sv;
    case TOK_TDD: return "TDD"sv;
    case TOK_TIN: return "TIN"sv;
    case TOK_TII: return "TII"sv;
    case TOK_TST: return "TST"sv;
    case TOK_eof: return "file ending"sv;
    }
}
#define asm_lex_TOK_KEY_CASES \

constexpr token_type_t TOK_LAST_STATE = 173;
constexpr token_type_t TOK_START = 370;
extern unsigned const lexer_ec_table[256];
extern token_type_t const lexer_transition_table[30392];
} // namespace asm_lex
