instr_def_t instr_defs[] =
{

    // ADC
    {
        .name = ADC_MODE_IMMEDIATE,
        .opname = ADC,
        .opcode = 105,
        .addr_mode = MODE_IMMEDIATE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ADC_MODE_ZERO_PAGE,
        .opname = ADC,
        .opcode = 101,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ADC_MODE_ZERO_PAGE_X,
        .opname = ADC,
        .opcode = 117,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ADC_MODE_ABSOLUTE,
        .opname = ADC,
        .opcode = 109,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ADC_MODE_ABSOLUTE_X,
        .opname = ADC,
        .opcode = 125,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ADC_MODE_ABSOLUTE_Y,
        .opname = ADC,
        .opcode = 121,
        .addr_mode = MODE_ABSOLUTE_Y,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ADC_MODE_INDIRECT_X,
        .opname = ADC,
        .opcode = 97,
        .addr_mode = MODE_INDIRECT_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ADC_MODE_INDIRECT_Y,
        .opname = ADC,
        .opcode = 113,
        .addr_mode = MODE_INDIRECT_Y,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // AND
    {
        .name = AND_MODE_IMMEDIATE,
        .opname = AND,
        .opcode = 41,
        .addr_mode = MODE_IMMEDIATE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = AND_MODE_ZERO_PAGE,
        .opname = AND,
        .opcode = 37,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = AND_MODE_ZERO_PAGE_X,
        .opname = AND,
        .opcode = 53,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = AND_MODE_ABSOLUTE,
        .opname = AND,
        .opcode = 45,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = AND_MODE_ABSOLUTE_X,
        .opname = AND,
        .opcode = 61,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = AND_MODE_ABSOLUTE_Y,
        .opname = AND,
        .opcode = 57,
        .addr_mode = MODE_ABSOLUTE_Y,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = AND_MODE_INDIRECT_X,
        .opname = AND,
        .opcode = 33,
        .addr_mode = MODE_INDIRECT_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = AND_MODE_INDIRECT_Y,
        .opname = AND,
        .opcode = 49,
        .addr_mode = MODE_INDIRECT_Y,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // ASL
    {
        .name = ASL_MODE_IMPLIED,
        .opname = ASL,
        .opcode = 10,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ASL_MODE_ZERO_PAGE,
        .opname = ASL,
        .opcode = 6,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ASL_MODE_ZERO_PAGE_X,
        .opname = ASL,
        .opcode = 22,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ASL_MODE_ABSOLUTE,
        .opname = ASL,
        .opcode = 14,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ASL_MODE_ABSOLUTE_X,
        .opname = ASL,
        .opcode = 30,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // BCC
    {
        .name = BCC_MODE_RELATIVE,
        .opname = BCC,
        .opcode = 144,
        .addr_mode = MODE_RELATIVE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // BCS
    {
        .name = BCS_MODE_RELATIVE,
        .opname = BCS,
        .opcode = 176,
        .addr_mode = MODE_RELATIVE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // BEQ
    {
        .name = BEQ_MODE_RELATIVE,
        .opname = BEQ,
        .opcode = 240,
        .addr_mode = MODE_RELATIVE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // BIT
    {
        .name = BIT_MODE_ZERO_PAGE,
        .opname = BIT,
        .opcode = 36,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = BIT_MODE_ABSOLUTE,
        .opname = BIT,
        .opcode = 44,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // BMI
    {
        .name = BMI_MODE_RELATIVE,
        .opname = BMI,
        .opcode = 48,
        .addr_mode = MODE_RELATIVE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // BNE
    {
        .name = BNE_MODE_RELATIVE,
        .opname = BNE,
        .opcode = 208,
        .addr_mode = MODE_RELATIVE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // BPL
    {
        .name = BPL_MODE_RELATIVE,
        .opname = BPL,
        .opcode = 16,
        .addr_mode = MODE_RELATIVE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // BRK
    {
        .name = BRK_MODE_IMPLIED,
        .opname = BRK,
        .opcode = 0,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // BVC
    {
        .name = BVC_MODE_RELATIVE,
        .opname = BVC,
        .opcode = 80,
        .addr_mode = MODE_RELATIVE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // BVS
    {
        .name = BVS_MODE_RELATIVE,
        .opname = BVS,
        .opcode = 112,
        .addr_mode = MODE_RELATIVE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // CLC
    {
        .name = CLC_MODE_IMPLIED,
        .opname = CLC,
        .opcode = 24,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // CLD
    {
        .name = CLD_MODE_IMPLIED,
        .opname = CLD,
        .opcode = 216,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // CLI
    {
        .name = CLI_MODE_IMPLIED,
        .opname = CLI,
        .opcode = 88,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // CLV
    {
        .name = CLV_MODE_IMPLIED,
        .opname = CLV,
        .opcode = 184,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // CMP
    {
        .name = CMP_MODE_IMMEDIATE,
        .opname = CMP,
        .opcode = 201,
        .addr_mode = MODE_IMMEDIATE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = CMP_MODE_ZERO_PAGE,
        .opname = CMP,
        .opcode = 197,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = CMP_MODE_ZERO_PAGE_X,
        .opname = CMP,
        .opcode = 213,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = CMP_MODE_ABSOLUTE,
        .opname = CMP,
        .opcode = 205,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = CMP_MODE_ABSOLUTE_X,
        .opname = CMP,
        .opcode = 221,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = CMP_MODE_ABSOLUTE_Y,
        .opname = CMP,
        .opcode = 217,
        .addr_mode = MODE_ABSOLUTE_Y,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = CMP_MODE_INDIRECT_X,
        .opname = CMP,
        .opcode = 193,
        .addr_mode = MODE_INDIRECT_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = CMP_MODE_INDIRECT_Y,
        .opname = CMP,
        .opcode = 209,
        .addr_mode = MODE_INDIRECT_Y,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // CPX
    {
        .name = CPX_MODE_IMMEDIATE,
        .opname = CPX,
        .opcode = 224,
        .addr_mode = MODE_IMMEDIATE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = CPX_MODE_ZERO_PAGE,
        .opname = CPX,
        .opcode = 228,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = CPX_MODE_ABSOLUTE,
        .opname = CPX,
        .opcode = 236,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // CPY
    {
        .name = CPY_MODE_IMMEDIATE,
        .opname = CPY,
        .opcode = 192,
        .addr_mode = MODE_IMMEDIATE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = CPY_MODE_ZERO_PAGE,
        .opname = CPY,
        .opcode = 196,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = CPY_MODE_ABSOLUTE,
        .opname = CPY,
        .opcode = 204,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // DEC
    {
        .name = DEC_MODE_ZERO_PAGE,
        .opname = DEC,
        .opcode = 198,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = DEC_MODE_ZERO_PAGE_X,
        .opname = DEC,
        .opcode = 214,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = DEC_MODE_ABSOLUTE,
        .opname = DEC,
        .opcode = 206,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = DEC_MODE_ABSOLUTE_X,
        .opname = DEC,
        .opcode = 222,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // DEX
    {
        .name = DEX_MODE_IMPLIED,
        .opname = DEX,
        .opcode = 202,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // DEY
    {
        .name = DEY_MODE_IMPLIED,
        .opname = DEY,
        .opcode = 136,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // EOR
    {
        .name = EOR_MODE_IMMEDIATE,
        .opname = EOR,
        .opcode = 73,
        .addr_mode = MODE_IMMEDIATE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = EOR_MODE_ZERO_PAGE,
        .opname = EOR,
        .opcode = 69,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = EOR_MODE_ZERO_PAGE_X,
        .opname = EOR,
        .opcode = 85,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = EOR_MODE_ABSOLUTE,
        .opname = EOR,
        .opcode = 77,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = EOR_MODE_ABSOLUTE_X,
        .opname = EOR,
        .opcode = 93,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = EOR_MODE_ABSOLUTE_Y,
        .opname = EOR,
        .opcode = 89,
        .addr_mode = MODE_ABSOLUTE_Y,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = EOR_MODE_INDIRECT_X,
        .opname = EOR,
        .opcode = 65,
        .addr_mode = MODE_INDIRECT_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = EOR_MODE_INDIRECT_Y,
        .opname = EOR,
        .opcode = 81,
        .addr_mode = MODE_INDIRECT_Y,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // INC
    {
        .name = INC_MODE_ZERO_PAGE,
        .opname = INC,
        .opcode = 230,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = INC_MODE_ZERO_PAGE_X,
        .opname = INC,
        .opcode = 246,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = INC_MODE_ABSOLUTE,
        .opname = INC,
        .opcode = 238,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = INC_MODE_ABSOLUTE_X,
        .opname = INC,
        .opcode = 254,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // INX
    {
        .name = INX_MODE_IMPLIED,
        .opname = INX,
        .opcode = 232,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // INY
    {
        .name = INY_MODE_IMPLIED,
        .opname = INY,
        .opcode = 200,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // JMP
    {
        .name = JMP_MODE_ABSOLUTE,
        .opname = JMP,
        .opcode = 76,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = JMP_MODE_INDIRECT,
        .opname = JMP,
        .opcode = 108,
        .addr_mode = MODE_INDIRECT,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // JSR
    {
        .name = JSR_MODE_ABSOLUTE,
        .opname = JSR,
        .opcode = 32,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // LDA
    {
        .name = LDA_MODE_IMMEDIATE,
        .opname = LDA,
        .opcode = 169,
        .addr_mode = MODE_IMMEDIATE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDA_MODE_ZERO_PAGE,
        .opname = LDA,
        .opcode = 165,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDA_MODE_ZERO_PAGE_X,
        .opname = LDA,
        .opcode = 181,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDA_MODE_ABSOLUTE,
        .opname = LDA,
        .opcode = 173,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDA_MODE_ABSOLUTE_X,
        .opname = LDA,
        .opcode = 189,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDA_MODE_ABSOLUTE_Y,
        .opname = LDA,
        .opcode = 185,
        .addr_mode = MODE_ABSOLUTE_Y,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDA_MODE_INDIRECT_X,
        .opname = LDA,
        .opcode = 161,
        .addr_mode = MODE_INDIRECT_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDA_MODE_INDIRECT_Y,
        .opname = LDA,
        .opcode = 177,
        .addr_mode = MODE_INDIRECT_Y,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // LDX
    {
        .name = LDX_MODE_IMMEDIATE,
        .opname = LDX,
        .opcode = 162,
        .addr_mode = MODE_IMMEDIATE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDX_MODE_ZERO_PAGE,
        .opname = LDX,
        .opcode = 166,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDX_MODE_ZERO_PAGE_Y,
        .opname = LDX,
        .opcode = 182,
        .addr_mode = MODE_ZERO_PAGE_Y,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDX_MODE_ABSOLUTE,
        .opname = LDX,
        .opcode = 174,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDX_MODE_ABSOLUTE_Y,
        .opname = LDX,
        .opcode = 190,
        .addr_mode = MODE_ABSOLUTE_Y,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // LDY
    {
        .name = LDY_MODE_IMMEDIATE,
        .opname = LDY,
        .opcode = 160,
        .addr_mode = MODE_IMMEDIATE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDY_MODE_ZERO_PAGE,
        .opname = LDY,
        .opcode = 164,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDY_MODE_ZERO_PAGE_X,
        .opname = LDY,
        .opcode = 180,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDY_MODE_ABSOLUTE,
        .opname = LDY,
        .opcode = 172,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LDY_MODE_ABSOLUTE_X,
        .opname = LDY,
        .opcode = 188,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // LSR
    {
        .name = LSR_MODE_IMPLIED,
        .opname = LSR,
        .opcode = 74,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LSR_MODE_ZERO_PAGE,
        .opname = LSR,
        .opcode = 70,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LSR_MODE_ZERO_PAGE_X,
        .opname = LSR,
        .opcode = 86,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LSR_MODE_ABSOLUTE,
        .opname = LSR,
        .opcode = 78,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = LSR_MODE_ABSOLUTE_X,
        .opname = LSR,
        .opcode = 94,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // NOP
    {
        .name = NOP_MODE_IMPLIED,
        .opname = NOP,
        .opcode = 234,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // ORA
    {
        .name = ORA_MODE_IMMEDIATE,
        .opname = ORA,
        .opcode = 9,
        .addr_mode = MODE_IMMEDIATE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ORA_MODE_ZERO_PAGE,
        .opname = ORA,
        .opcode = 5,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ORA_MODE_ZERO_PAGE_X,
        .opname = ORA,
        .opcode = 21,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ORA_MODE_ABSOLUTE,
        .opname = ORA,
        .opcode = 13,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ORA_MODE_ABSOLUTE_X,
        .opname = ORA,
        .opcode = 29,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ORA_MODE_ABSOLUTE_Y,
        .opname = ORA,
        .opcode = 25,
        .addr_mode = MODE_ABSOLUTE_Y,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ORA_MODE_INDIRECT_X,
        .opname = ORA,
        .opcode = 1,
        .addr_mode = MODE_INDIRECT_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ORA_MODE_INDIRECT_Y,
        .opname = ORA,
        .opcode = 17,
        .addr_mode = MODE_INDIRECT_Y,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // PHA
    {
        .name = PHA_MODE_IMPLIED,
        .opname = PHA,
        .opcode = 72,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // PHP
    {
        .name = PHP_MODE_IMPLIED,
        .opname = PHP,
        .opcode = 8,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // PLA
    {
        .name = PLA_MODE_IMPLIED,
        .opname = PLA,
        .opcode = 104,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // PLP
    {
        .name = PLP_MODE_IMPLIED,
        .opname = PLP,
        .opcode = 40,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // ROL
    {
        .name = ROL_MODE_IMPLIED,
        .opname = ROL,
        .opcode = 42,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ROL_MODE_ZERO_PAGE,
        .opname = ROL,
        .opcode = 38,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ROL_MODE_ZERO_PAGE_X,
        .opname = ROL,
        .opcode = 54,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ROL_MODE_ABSOLUTE,
        .opname = ROL,
        .opcode = 46,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ROL_MODE_ABSOLUTE_X,
        .opname = ROL,
        .opcode = 62,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // ROR
    {
        .name = ROR_MODE_IMPLIED,
        .opname = ROR,
        .opcode = 106,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ROR_MODE_ZERO_PAGE,
        .opname = ROR,
        .opcode = 102,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ROR_MODE_ZERO_PAGE_X,
        .opname = ROR,
        .opcode = 118,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ROR_MODE_ABSOLUTE,
        .opname = ROR,
        .opcode = 110,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = ROR_MODE_ABSOLUTE_X,
        .opname = ROR,
        .opcode = 126,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // RTI
    {
        .name = RTI_MODE_IMPLIED,
        .opname = RTI,
        .opcode = 64,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // RTS
    {
        .name = RTS_MODE_IMPLIED,
        .opname = RTS,
        .opcode = 96,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // SBC
    {
        .name = SBC_MODE_IMMEDIATE,
        .opname = SBC,
        .opcode = 233,
        .addr_mode = MODE_IMMEDIATE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = SBC_MODE_ZERO_PAGE,
        .opname = SBC,
        .opcode = 229,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = SBC_MODE_ZERO_PAGE_X,
        .opname = SBC,
        .opcode = 245,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = SBC_MODE_ABSOLUTE,
        .opname = SBC,
        .opcode = 237,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = SBC_MODE_ABSOLUTE_X,
        .opname = SBC,
        .opcode = 253,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = SBC_MODE_ABSOLUTE_Y,
        .opname = SBC,
        .opcode = 249,
        .addr_mode = MODE_ABSOLUTE_Y,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = SBC_MODE_INDIRECT_X,
        .opname = SBC,
        .opcode = 225,
        .addr_mode = MODE_INDIRECT_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = SBC_MODE_INDIRECT_Y,
        .opname = SBC,
        .opcode = 241,
        .addr_mode = MODE_INDIRECT_Y,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // SEC
    {
        .name = SEC_MODE_IMPLIED,
        .opname = SEC,
        .opcode = 56,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // SED
    {
        .name = SED_MODE_IMPLIED,
        .opname = SED,
        .opcode = 248,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // SEI
    {
        .name = SEI_MODE_IMPLIED,
        .opname = SEI,
        .opcode = 120,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // STA
    {
        .name = STA_MODE_ZERO_PAGE,
        .opname = STA,
        .opcode = 133,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = STA_MODE_ZERO_PAGE_X,
        .opname = STA,
        .opcode = 149,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = STA_MODE_ABSOLUTE,
        .opname = STA,
        .opcode = 141,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = STA_MODE_ABSOLUTE_X,
        .opname = STA,
        .opcode = 157,
        .addr_mode = MODE_ABSOLUTE_X,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = STA_MODE_ABSOLUTE_Y,
        .opname = STA,
        .opcode = 153,
        .addr_mode = MODE_ABSOLUTE_Y,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = STA_MODE_INDIRECT_X,
        .opname = STA,
        .opcode = 129,
        .addr_mode = MODE_INDIRECT_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = STA_MODE_INDIRECT_Y,
        .opname = STA,
        .opcode = 145,
        .addr_mode = MODE_INDIRECT_Y,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // STX
    {
        .name = STX_MODE_ZERO_PAGE,
        .opname = STX,
        .opcode = 134,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = STX_MODE_ZERO_PAGE_Y,
        .opname = STX,
        .opcode = 150,
        .addr_mode = MODE_ZERO_PAGE_Y,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = STX_MODE_ABSOLUTE,
        .opname = STX,
        .opcode = 142,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // STY
    {
        .name = STY_MODE_ZERO_PAGE,
        .opname = STY,
        .opcode = 132,
        .addr_mode = MODE_ZERO_PAGE,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = STY_MODE_ZERO_PAGE_X,
        .opname = STY,
        .opcode = 148,
        .addr_mode = MODE_ZERO_PAGE_X,
        .size = 2,
        .cycles = 2,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
    {
        .name = STY_MODE_ABSOLUTE,
        .opname = STY,
        .opcode = 140,
        .addr_mode = MODE_ABSOLUTE,
        .size = 3,
        .cycles = 3,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // TAX
    {
        .name = TAX_MODE_IMPLIED,
        .opname = TAX,
        .opcode = 170,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // TAY
    {
        .name = TAY_MODE_IMPLIED,
        .opname = TAY,
        .opcode = 168,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // TSX
    {
        .name = TSX_MODE_IMPLIED,
        .opname = TSX,
        .opcode = 186,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // TXA
    {
        .name = TXA_MODE_IMPLIED,
        .opname = TXA,
        .opcode = 138,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // TXS
    {
        .name = TXS_MODE_IMPLIED,
        .opname = TXS,
        .opcode = 154,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },

    // TYA
    {
        .name = TYA_MODE_IMPLIED,
        .opname = TYA,
        .opcode = 152,
        .addr_mode = MODE_IMPLIED,
        .size = 1,
        .cycles = 1,
        .implicit_regs = 0,
        .arg_regs = 0,
        .out_regs = 0,
    },
};
